MODULE_NAME=test
INPUT_DIR=cpp
OUTPUT_DIR=src/wasm
INCLUDE_DIR=include

emcc ${INPUT_DIR}/${MODULE_NAME}.cpp -o ${OUTPUT_DIR}/${MODULE_NAME}.js -sEXPORT_ES6=1 -sEXPORT_NAME="\"${MODULE_NAME}\"" -sENVIRONMENT="web" -sEXPORTED_RUNTIME_METHODS=ccall,cwrap -I ${INPUT_DIR}/${INCLUDE_DIR}/glm