MODULE_NAME=ascii-renderer
EXPORT_NAME=asciiRenderer
INPUT_DIR=cpp
OUTPUT_DIR=src/wasm
INCLUDE_DIR=include

emcc ${INPUT_DIR}/${MODULE_NAME}.cpp -o ${OUTPUT_DIR}/${MODULE_NAME}.js -sEXPORT_ES6=1 -sEXPORT_NAME="\"${EXPORT_NAME}\"" -sENVIRONMENT="web" -sEXPORTED_RUNTIME_METHODS=ccall,cwrap -I ${INPUT_DIR}/${INCLUDE_DIR}/glm
