name: Build

on: [push, pull_request]
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install emscripten
        uses: mymindstorm/setup-emsdk@v14

      - name: Build cpp
        run: |
          cd web-frontend
          bash build.sh
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build frontend
        run: |
          cd web-frontend
          npm install
          npm run build
    
      - name: Upload build artifact
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
            name: production-assets
            path: web-frontend/dist/
            retention-days: 1